SET(${REPOSITORY_NAME}_VERSION 2.0.0)
SET(${REPOSITORY_NAME}_MAJOR_VERSION 2)
SET(${REPOSITORY_NAME}_MAJOR_MINOR_VERSION 020000)
SET(${REPOSITORY_NAME}_VERSION_STRING "2.0.0 (Dev)")
# Switch the following OFF for a release.
SET(${REPOSITORY_NAME}_ENABLE_DEVELOPMENT_MODE_DEFAULT ON)
